language: java

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE movie_website;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres

sudo: enabled
jdk:
- oraclejdk8
